In [19]:
import sys
import os
print('executable:', sys.executable)
print('site-packages exists:', os.path.exists(os.path.join(sys.prefix, 'Lib', 'site-packages')))
print('\n'.join(sys.path[:5]))

executable: d:\f1-race-intelligence\.venv-1\Scripts\python.exe
site-packages exists: True
C:\Program Files\Python312\python312.zip
C:\Program Files\Python312\DLLs
C:\Program Files\Python312\Lib
C:\Program Files\Python312
d:\f1-race-intelligence\.venv-1

In [20]:
import fastf1
import pandas as pd

In [21]:
fastf1.Cache.enable_cache('../cache')

In [22]:
quali = fastf1.get_session(2025, 'Canada', 'Q')
quali.load()

quali_results = quali.results
quali_results[['FullName', 'Position']]

core           INFO 	Loading data for Canadian Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '81', '12', '44', '14', '4', '16', '6', '23', '22', '43', '27', '87', '31', '5', '55', '18', '30', '10']

             FullName  Position
63     George Russell       1.0
1      Max Verstappen       2.0
81      Oscar Piastri       3.0
12     Kimi Antonelli       4.0
44     Lewis Hamilton       5.0
14    Fernando Alonso       6.0
4        Lando Norris       7.0
16    Charles Leclerc       8.0
6        Isack Hadjar       9.0
23    Alexander Albon      10.0
22       Yuki Tsunoda      11.0
43   Franco Colapinto      12.0
27    Nico Hulkenberg      13.0
87     Oliver Bearman      14.0
31       Esteban Ocon      15.0
5   Gabriel Bortoleto      16.0
55       Carlos Sainz      17.0
18       Lance Stroll      18.0
30        Liam Lawson      19.0
10       Pierre Gasly      20.0

In [23]:
session = fastf1.get_session(2025, 'Canada', 'R')
session.load()

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '1', '12', '81', '16', '44', '14', '27', '31', '55', '87', '22', '43', '5', '10', '6', '18', '4', '30', '23']

In [24]:
results = session.results
results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:31:52.688000,Finished,25.0,70.0
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:00.228000,Finished,18.0,70.0
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:01.014000,Finished,15.0,70.0
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,4.0,4,3.0,NaT,NaT,NaT,0 days 00:00:02.109000,Finished,12.0,70.0
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,5.0,5,8.0,NaT,NaT,NaT,0 days 00:00:03.442000,Finished,10.0,70.0

In [25]:
fp2 = fastf1.get_session(2025, 'Canada', 'FP2')
fp2.load()

core           INFO 	Loading data for Canadian Grand Prix - Practice 2 [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 16
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 16)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '43', '44', '55', '63', '81', '87']

In [26]:
laps = fp2.laps
laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:19:58.919000,VER,1,0 days 00:01:49.496000,1.0,1.0,0 days 00:18:13.324000,NaT,0 days 00:00:41.239000,0 days 00:00:25.513000,...,True,Red Bull Racing,0 days 00:18:13.324000,2025-06-13 21:03:24.047,1,NaN,False,,False,False
1,0 days 00:21:41.390000,VER,1,0 days 00:01:42.471000,2.0,1.0,NaT,NaT,0 days 00:00:24.423000,0 days 00:00:33.003000,...,True,Red Bull Racing,0 days 00:19:58.919000,2025-06-13 21:05:09.642,12,NaN,False,,False,True
2,0 days 00:22:54.819000,VER,1,0 days 00:01:13.429000,3.0,1.0,NaT,NaT,0 days 00:00:20.526000,0 days 00:00:23.357000,...,True,Red Bull Racing,0 days 00:21:41.390000,2025-06-13 21:06:52.113,1,NaN,False,,False,True
3,0 days 00:24:52.985000,VER,1,0 days 00:01:58.166000,4.0,1.0,NaT,NaT,0 days 00:00:36.944000,0 days 00:00:44.880000,...,True,Red Bull Racing,0 days 00:22:54.819000,2025-06-13 21:08:05.542,12,NaN,False,,False,True
4,0 days 00:26:06.231000,VER,1,0 days 00:01:13.246000,5.0,1.0,NaT,NaT,0 days 00:00:20.529000,0 days 00:00:23.321000,...,True,Red Bull Racing,0 days 00:24:52.985000,2025-06-13 21:10:03.708,1,NaN,False,,False,True

In [27]:
best_laps = laps.groupby('Driver')['LapTime'].min().reset_index()
best_laps

   Driver                LapTime
0     ALB 0 days 00:01:12.445000
1     ALO 0 days 00:01:12.458000
2     ANT 0 days 00:01:12.411000
3     BEA 0 days 00:01:13.080000
4     BOR 0 days 00:01:12.896000
5     COL 0 days 00:01:13.898000
6     GAS 0 days 00:01:12.874000
7     HAD 0 days 00:01:12.799000
8     HAM 0 days 00:01:12.653000
9     HUL 0 days 00:01:12.914000
10    LAW 0 days 00:01:12.751000
11    NOR 0 days 00:01:12.151000
12    OCO 0 days 00:01:13.175000
13    PIA 0 days 00:01:12.562000
14    RUS 0 days 00:01:12.123000
15    SAI 0 days 00:01:12.631000
16    STR 0 days 00:01:49.253000
17    TSU 0 days 00:01:12.939000
18    VER 0 days 00:01:12.666000

In [28]:
# Race results
race_df = results[['FullName', 'Position']].copy()

# Qualifying results
quali_df = quali_results[['FullName', 'Position']].copy()
quali_df.rename(columns={'Position': 'QualiPosition'}, inplace=True)

# Practice pace
best_laps.rename(columns={
    'Driver': 'Abbreviation',
    'LapTime': 'BestFP2Lap'
}, inplace=True)

# Driver abbreviation mapping
driver_map = quali_results[['FullName', 'Abbreviation']]

# Merge practice pace with names
pace_df = pd.merge(driver_map, best_laps, on='Abbreviation')

# Merge all datasets
dataset = pd.merge(race_df, quali_df, on='FullName')
dataset = pd.merge(dataset, pace_df[['FullName', 'BestFP2Lap']], on='FullName')

dataset.head()

         FullName  Position  QualiPosition             BestFP2Lap
0  George Russell       1.0            1.0 0 days 00:01:12.123000
1  Max Verstappen       2.0            2.0 0 days 00:01:12.666000
2  Kimi Antonelli       3.0            4.0 0 days 00:01:12.411000
3   Oscar Piastri       4.0            3.0 0 days 00:01:12.562000
4  Lewis Hamilton       6.0            5.0 0 days 00:01:12.653000

In [29]:
dataset['BestFP2LapSeconds'] = dataset['BestFP2Lap'].dt.total_seconds()

dataset.head()

,FullName,Position,QualiPosition,BestFP2Lap,BestFP2LapSeconds
0,George Russell,1.0,1.0,0 days 00:01:12.123000,72.123
1,Max Verstappen,2.0,2.0,0 days 00:01:12.666000,72.666
2,Kimi Antonelli,3.0,4.0,0 days 00:01:12.411000,72.411
3,Oscar Piastri,4.0,3.0,0 days 00:01:12.562000,72.562
4,Lewis Hamilton,6.0,5.0,0 days 00:01:12.653000,72.653

In [30]:
final_dataset = dataset[['QualiPosition', 'BestFP2LapSeconds', 'Position']]

final_dataset.head()

   QualiPosition  BestFP2LapSeconds  Position
0            1.0             72.123       1.0
1            2.0             72.666       2.0
2            4.0             72.411       3.0
3            3.0             72.562       4.0
4            5.0             72.653       6.0

In [32]:
final_dataset.to_csv('../data/canada_2025_dataset.csv', index=False)

In [33]:
final_dataset.head()

   QualiPosition  BestFP2LapSeconds  Position
0            1.0             72.123       1.0
1            2.0             72.666       2.0
2            4.0             72.411       3.0
3            3.0             72.562       4.0
4            5.0             72.653       6.0